# Generated by Django 3.0.8 on 2020-08-13 12:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20200813_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_para', models.IntegerField()),
                ('data', models.TextField()),
                ('img', models.ImageField(blank=True, upload_to='../media/post_picture')),
                ('img_title', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='post',
            old_name='img',
            new_name='img_main',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 13, 19, 51, 4, 362433)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 13, 19, 51, 4, 361432)),
        ),
        migrations.DeleteModel(
            name='image',
        ),
        migrations.AddField(
            model_name='content',
            name='post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Post'),
        ),
        migrations.AlterUniqueTogether(
            name='content',
            unique_together={('post_id', 'number_para')},
        ),
    ]
