# Generated by Django 3.0.8 on 2020-08-13 13:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20200813_1951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='count',
            new_name='total_post',
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 13, 20, 23, 50, 266831)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 13, 20, 23, 50, 265833)),
        ),
    ]
