# Generated by Django 3.0.8 on 2020-08-16 13:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_auto_20200813_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 16, 20, 48, 29, 72721)),
        ),
        migrations.AlterField(
            model_name='content',
            name='img',
            field=models.ImageField(blank=True, upload_to='post_picture'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 16, 20, 48, 29, 71724)),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(max_length=800),
        ),
        migrations.AlterField(
            model_name='post',
            name='img_main',
            field=models.ImageField(upload_to='post_picture'),
        ),
    ]
