# Generated by Django 3.0.8 on 2020-08-25 12:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_auto_20200816_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 25, 19, 8, 37, 434446)),
        ),
        migrations.AlterField(
            model_name='content',
            name='img',
            field=models.ImageField(blank=True, upload_to='home/media/post_picture'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 25, 19, 8, 37, 433447)),
        ),
    ]
