# Generated by Django 3.0.8 on 2020-08-27 13:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_auto_20200825_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reply_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='post.Comment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 27, 20, 23, 19, 8451)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 27, 20, 23, 19, 8451)),
        ),
    ]
