# Generated by Django 3.0.8 on 2020-08-30 15:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_auto_20200830_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 30, 22, 56, 57, 238725)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 30, 22, 56, 57, 237725)),
        ),
        migrations.DeleteModel(
            name='Content',
        ),
    ]
