# Generated by Django 3.0.8 on 2020-08-13 13:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200813_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 13, 20, 23, 50, 262842)),
        ),
    ]
