# Generated by Django 3.0.8 on 2020-08-30 14:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20200827_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 30, 21, 26, 0, 236272)),
        ),
    ]
