# Generated by Django 3.0.8 on 2020-10-11 10:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20200915_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 11, 17, 50, 58, 412302)),
        ),
    ]
