# Generated by Django 3.0.8 on 2020-10-15 02:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0031_auto_20201014_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 15, 9, 38, 24, 465044)),
        ),
    ]
